### ISSUE TITLE
Collection::shuffle()-conflict in the latest Laravel

### ISSUE THREAD

**Issue by Blizzke** [Anahkiasen/arrounded#35]
The `Collection` in the latest version of Laravel has its own [`shuffle()` method](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Collection.php#L843-L858). Unfortunately it's incompatible, causing a conflict.

**Comment by bramdevries** [comment]
Released in https://github.com/Anahkiasen/arrounded/releases/tag/0.9.1
